version: '3.9'
services:
  postgres:
    image: postgres:15.3
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "5432:5432"